TICKER_SUFFIXES = {
    'FR': 'PA',
    'CH': 'SW',
    'DK': 'CO',
    'ES': 'MC',
    'FI': 'HE',
    'DE': 'DE',
    'SE': 'ST',
    'NO': 'OL',
    'PL': 'WA',
    'BE': 'BR',
    'NL': 'AS',
    'PT': 'LS',
    'IT': 'MI',
    'UK': 'L',
}

PIOTROSKI_OUT_COLS = ['ticker',
                      'country',
                      'name',
                      'piotroskiFScore',
                      'trailingPE',
                      'lastAsofDate',
                      'industry',
                      'sector',
                      'currency',
                      'dividendRate',
                      'volume',
                      'marketCap',
                      'twoHundredDayAverage',
                      'website',
                      'longBusinessSummary',
                      ]
